(()=>{
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const loader=$('.site-loader'); const hide=()=>loader?.classList.add('is-hidden'); addEventListener('load',()=>setTimeout(hide,450)); setTimeout(hide,1700);
const reveals=$$('.reveal,.image-reveal');
if('IntersectionObserver' in window&&!reduce){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');io.unobserve(e.target)}}),{threshold:.04,rootMargin:'0px 0px -5%'});reveals.forEach((el,i)=>{el.style.transitionDelay=`${Math.min((i%5)*70,280)}ms`;io.observe(el)})}else reveals.forEach(e=>e.classList.add('in-view'));
const menu=$('.menu-toggle'),nav=$('.nav');menu?.addEventListener('click',()=>{const open=menu.classList.toggle('open');nav?.classList.toggle('open',open);menu.setAttribute('aria-expanded',open)});$$('.nav a').forEach(a=>a.addEventListener('click',()=>{menu?.classList.remove('open');nav?.classList.remove('open')}));
const bar=$('.progress-bar');function progress(){const max=document.documentElement.scrollHeight-innerHeight;bar.style.width=(max>0?scrollY/max*100:0)+'%';$('.back-top')?.classList.toggle('show',scrollY>650)}addEventListener('scroll',progress,{passive:true});progress();$('.back-top')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
const links=$$('.nav a'),sections=$$('main section[id]');if('IntersectionObserver'in window){const so=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>so.observe(s))}
$$('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{$$('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;$$('.project').forEach(p=>p.classList.toggle('is-filtered',f!=='all'&&p.dataset.category!==f));refreshGallery()}));
let gallery=[],index=0;const box=$('.lightbox'),boxImg=$('.lightbox img'),cap=$('.lightbox figcaption');function refreshGallery(){gallery=$$('.project-pages img,.hero-image img').filter(im=>!im.closest('.project.is-filtered'));gallery.forEach((im,i)=>im.onclick=()=>open(i))}function open(i){index=i;const im=gallery[index];if(!im)return;boxImg.src=im.currentSrc||im.src;boxImg.alt=im.alt;cap.textContent=im.alt;box.classList.add('open');box.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function close(){box.classList.remove('open');box.setAttribute('aria-hidden','true');document.body.style.overflow=''}function move(d){index=(index+d+gallery.length)%gallery.length;open(index)}refreshGallery();$('.lightbox-close')?.addEventListener('click',close);$('.lightbox-prev')?.addEventListener('click',()=>move(-1));$('.lightbox-next')?.addEventListener('click',()=>move(1));box?.addEventListener('click',e=>{if(e.target===box)close()});addEventListener('keydown',e=>{if(!box.classList.contains('open'))return;if(e.key==='Escape')close();if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1)});
const cursor=$('.cursor');if(cursor&&matchMedia('(pointer:fine)').matches&&!reduce){const text=cursor.querySelector('span');let mx=innerWidth/2,my=innerHeight/2,cx=mx,cy=my;addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY});(function tick(){cx+=(mx-cx)*.15;cy+=(my-cy)*.15;cursor.style.left=cx+'px';cursor.style.top=cy+'px';requestAnimationFrame(tick)})();const bind=()=>$$('img,.scroll-link,.contact-row a').forEach(el=>{el.addEventListener('mouseenter',()=>{text.textContent=el.matches('img')?'VIEW':'OPEN';cursor.classList.add('visible')});el.addEventListener('mouseleave',()=>cursor.classList.remove('visible'))});bind()}
const hero=$('.hero-image');if(hero&&!reduce&&matchMedia('(pointer:fine)').matches){const im=hero.querySelector('img');hero.addEventListener('mousemove',e=>{const r=hero.getBoundingClientRect(),x=e.clientX/r.width-r.left/r.width-.5,y=e.clientY/r.height-r.top/r.height-.5;im.style.transform=`scale(1.035) translate(${x*8}px,${y*8}px)`});hero.addEventListener('mouseleave',()=>im.style.transform='')}
if(!reduce&&matchMedia('(pointer:fine)').matches){$$('.project-pages img').forEach(im=>im.addEventListener('mousemove',e=>{const r=im.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;im.style.transform=`perspective(900px) rotateX(${y*-2}deg) rotateY(${x*2}deg) scale(1.018)`;});$$('.project-pages img').forEach(im=>im.addEventListener('mouseleave',()=>im.style.transform=''))}
$$('.scroll-link,.contact-row a,.brand').forEach(el=>{if(!matchMedia('(pointer:fine)').matches||reduce)return;el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.1}px,${(e.clientY-r.top-r.height/2)*.1}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});
})();
